### ISSUE TITLE
ckpt error

### ISSUE THREAD

**Issue by ice-cream567** [CalvinYang0/CRNet#1]
In my test code, executing state_dict = torch.load(load_path, map_location=self.device) throws the following error:

Traceback (most recent call last):
  File "D:\anaconda3\envs\asd\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda3\envs\asd\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load

It might be due to file corruption or other reasons. Could you please check and re-upload the file? Additionally, could you provide the training data?

**Comment by CalvinYang0** [comment]
Based on your error, I successfully loaded the weight file in my environment. I believe your issue might be due to the PyTorch version. I am using PyTorch 2.0. If you think the problem is with a corrupted file after checking, please leave your email, and I will send you a new copy. Additionally, I have updated the dataset download link in the README.

**Comment by GaoYuzhuo** [comment]
I encountered the same problem in PyTorch 2.0.1. Could you please send me a weight file copy? Many thanks. 

Email: gyzhbxg@gmail.com 

> Based on your error, I successfully loaded the weight file in my environment. I believe your issue might be due to the PyTorch version. I am using PyTorch 2.0. If you think the problem is with a corrupted file after checking, please leave your email, and I will send you a new copy. Additionally, I have updated the dataset download link in the README.

**Comment by ice-cream567** [comment]
First of all, thank you for your help. I would like to leave my email address 1964006570@qq.com@qq.com to receive a copy of the weight file.

**Comment by CalvinYang0** [comment]
> First of all, thank you for your help. I would like to leave my email address [1964006570@qq.com](mailto:1964006570@qq.com) to receive a copy of the weight file.

I have already sent the file via email. Is the issue still present?

**Comment by CalvinYang0** [comment]
> I encountered the same problem in PyTorch 2.0.1. Could you please send me a weight file copy? Many thanks.
> 
> Email: [gyzhbxg@gmail.com](mailto:gyzhbxg@gmail.com)
> 
> > Based on your error, I successfully loaded the weight file in my environment. I believe your issue might be due to the PyTorch version. I am using PyTorch 2.0. If you think the problem is with a corrupted file after checking, please leave your email, and I will send you a new copy. Additionally, I have updated the dataset download link in the README.

I have already sent the file via email. Is the issue still present?

**Comment by GaoYuzhuo** [comment]
It works now. Thank you so much.

**Comment by tongji-rkr** [comment]
May I ask which python version, pytorch version and the corresponding CUDA version you use? @CalvinYang0
