### ISSUE TITLE
'MaxPool Separation' Not Found

### ISSUE THREAD

**Issue by ice-cream567** [CalvinYang0/CRNet#2]
Hello,

I noticed in Figure 2 of the paper that MaxPool operations are used in the high-frequency enhancement module. However, in the code:
x1 = self.updown(x1, raw)
x1 = self.downup(x1, raw)
only AvgPool is used. Could you please clarify if this is an oversight? If so, how significant is this oversight? Specifically, would the difference between average pooling and max pooling have a substantial impact on the network's performance?

Thank you.

**Comment by ice-cream567** [comment]
TK!

**Comment by CalvinYang0** [comment]
感谢您的提醒和理解，我会尽快更正这个错误。
